name: easy_ride
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.7.0
  flutter_svg: ^1.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.0.9
  shared_preferences: ^2.3.1
  flutter_secure_storage: ^9.2.2
  logger: ^2.4.0
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  dio: ^5.5.0+1
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/model3.svg
    - assets/images/model3.png
    - assets/images/appbar_car.svg
